### ISSUE TITLE
How can i get the maps data?

### ISSUE THREAD

**Issue by zhjygit** [aresta/OSM_Extract#2]
I have compiled the esp32_gps project on my esp32s3-lcd 4.3 device.
But i don't know how to use the osm_extract code to get the files.
Can you give some details to get the files,and then save them to SD card.
Thanks a lot.

**Comment by aresta** [comment]
Hello,  I have to document it better, it's still work in progress. It's a manual process for the moment.
To generate the map files first you have to download the openstreetmap PBF file of your country or area, for example from here: https://download.geofabrik.de/  put the PBF file in the /pbf folder.

Then you have to clip the PBF file into a PBF of a smaller area, for performance as the initial PBF is very big:
First define your smaller area here: /conf/clip_area.geojson  You can adjust it manually, it's just a rectangle with lat/lon coordinates. Or you can use this web tool to generate the rectangle over the map: http://geojson.io/
Then:
/maps/osmium extract --strategy=smart -p ../conf/clip_area.geojson /pbf/big-file.osm.pbf -o /pbf/clipped.pbf
To do this you need osmium. Or better if you have docker just launch the docker container, it has all the tools and libraries needed.

Then you should have the smaller area PBF file: /pbf/clipped.pbf
Next step is to extract the lines and polygons from the PBF file, with the script: /scripts/pbf_to_geojson.sh
It will generate 2 files: /maps/polygons.geojson and /maps/lines.geojson

And the last step is to execute: /scripts/extract_features.py  to generate all the map files, you have to copy them to the SD card.

This is a work in progress but with some adjustments and testing should work in your system. I'm now also moving to ESP32-S3, I'll update the code, it should be just change the GPIO pin numbers and maybe adjust some library settings.
I hope it helps. Let me know if you have problems or find errors.

**Comment by zhjygit** [comment]
Ok, thanks sir, I will try and feedback my practice on the esp32s3 board.

**Comment by zhjygit** [comment]
osmium extract --strategy=smart -p ../conf/clip_area.geojson ./pbf/china-latest.osm.pbf -o ./pbf/clipped.pbf
![image](https://github.com/aresta/OSM_Extract/assets/44870751/0110ac11-0671-4f24-9a9e-9463b0282575)

**Comment by aresta** [comment]
Make sure that the file: clip_area.geojson has the correct format, like the example one in the /conf folder.

**Comment by secret-agent313** [comment]
Hello,Where do I enter this?
/maps/osmium extract --strategy=smart -p ../conf/clip_area.geojson /pbf/big-file.osm.pbf -o /pbf/clipped.pbf

**Comment by zhjygit** [comment]
you have to prepare for the environment for osm_extract.
  via docker according to the dockfile;
  or you can prepare the environment in ubuntu 18.04 by yourself according to the command in the dockfile.
 if you finished the environment, then, all of the command or python scripts in this project can be executed, such as "osmium extract --strategy=smart -p ../conf/clip_area.geojson /pbf/big-file.osm.pbf -o /pbf/clipped.pbf" after "cd to maps/"
Maybe there are some errors in the python scripts, you can correct via the errors promption.

**Comment by secret-agent313** [comment]
Do you have a tutorial video?  After using the scripts/pbf_to_geojson.sh   file, a message appears in cmd, but nothing is generated
This part is executed:
if [ $# -eq 0 ]; then
    echo " No arguments provided."
    echo " Usage:"
    echo "      $0 <min_lon> <min_lat> <max_lon> <max_lat> <pbf input file> <output file name>"
    echo ""
    exit 1

**Comment by raxpww** [comment]
Likewise. We are also trying to get a set of FMP map files from a small PBF file. The discussion above has clarified the process a bit. But there is no success. The extract_features.py script does not run:

XXX@XXX:~/XXX/map/OSM_Extract/scripts$ ./extract_features.py 30.21479663274244 50.306054423136645 30.85481801454421 50.59339450420998 outfile.fmp
Traceback (most recent call last):
   File "/home/XXX/map/OSM_Extract/scripts/./extract_features.py", line 2, in <module>
     from funcs import process_features, clip_lines, clip_polygons, style_features, render_map, lat2y, lon2x
   File "/home/XXX/map/OSM_Extract/scripts/funcs.py", line 1, in <module>
     from shapely import geometry, LineString, LinearRing, Polygon, MultiPolygon, MultiLineString, Point, intersection
ImportError: cannot import name 'LineString' from 'shapely' (/usr/lib/python3/dist-packages/shapely/__init__.py)

**Comment by aresta** [comment]
Hi, I have added a brief explanation and example in the README. It is still a manual and not very convenient system, still work in progress.
Try and ask here if you have questions or problems.
