### ISSUE TITLE
Issues and how to resolve them

### ISSUE THREAD

**Issue by vladbondarenko** [aresta/OSM_Extract#3]
Hi,

First of all you need to install newest version of shapely, its 2.0.3

pip install shapely==2.0.3

then you need to modify funcs.py (first 2 lines)

from shapely import geometry, intersection
from shapely.geometry import LineString, LinearRing, Polygon, MultiPolygon, MultiLineString, Point

then you need to modify extract_features.py

CONF_FEATURES = '../conf/conf_extract.yaml'
CONF_STYLES = '../conf/conf_styles.yaml'
MAP_FOLDER = '../maps/mymap'

initialy there was /conf/conf_extract.yaml (without ../ at the beginning and that tells absolute path from the root /, not from the cloned dir)

and after that scripts started to work.

**Comment by aresta** [comment]
Ok, thank you. Some of this topics are because it is configured to work with the docker container, to avoid configuration differences. But actually it's easy to make it working directly without docker.
