### ISSUE TITLE
extract_features.py

### ISSUE THREAD

**Issue by cayleyflyer** [aresta/OSM_Extract#4]
HI
thanks for sharing your code.

when I run "extract_features.py"   with the parameters from the  "clip_area,geojson" file.   
Using the command line  "python3 extract_features.py 1.685955 41.225810 2.089054 41.604818 "
line 11 in "extract_features.py"  causes an error,,,,"indexError: out of range. This is because I have not provided  a "geojson prefix name".
My question is what is the "geojson prefix name" ?

if I add my own prefix name changing files  "lines_geojson" and "polygons_geojson"  files,  to "lines_lines.geojson" and "lines_polygons.geojson" and then run 
"python3 extract_features.py 1.685955 41.225810 2.089054 41.604818 lines"  

The code runs Step 1/5 and Step 2/5, However it does not run beyond this block of code in "extract_features.py"

59        # clip features to the block area
60        clipped_lines = clip_lines( lines, mapblock_bbox)
61       clipped_polygons = clip_polygons( polygons, mapblock_bbox)
62        print ("line62")
63        if len(clipped_lines) == 0 and len( clipped_polygons) == 0:
64        done += 1
65        continue

if I comment out line 65 to  "#continue" the whole code runs and creates  a set  of empty map files and blank images. 

My second question is
I have managed to clip a pbf file to the size I want to use, using osmium
"osmium extract --strategy=smart -p ../conf/clip_area.geojson /pbf/.osm.pbf -o /pbf/clipped.pbf"
 
however the pbf_to_geojson.sh script returns an error "./pbf_to_geojson.sh: line 30: syntax error: unexpected end of file"
so i can not create my own line and polygon geojson files for my clipped area.

any help would be appreciated

kind regards
Jeremy

**Comment by aresta** [comment]
Hi, the prefix name is the initial part of the name for the lines and polygons files.  For example if you put '/maps/test' then it will look for the next two files:  /maps/test_lines.geojson,  /maps/test_polygons.geojson

These two files are intermediate data files, and have to be created before with the pbf_to_geojson.sh script, with the same prefix name:

For example, the complete process:
```
min_lon=123
min_lat=123
max_lon=123
max_lat=123

./pbf_to_geojson.sh $min_lon $min_lat $max_lon $max_lat /pbf/sp.pbf /maps/test
echo "PBF extract done"

./extract_features.py $min_lon $min_lat $max_lon $max_lat /maps/test
echo "Map files created"
```
I'll add to the readme
